### ISSUE TITLE
standard_init_linux.go:230: exec user process caused: exec format error

### ISSUE THREAD

**Issue by bbhxwl** [appleboy/drone-scp#146]
![image](https://user-images.githubusercontent.com/26525599/210167237-9ee6265e-1d6b-461d-957c-6e175e92ca1a.png)

**Comment by leytilera** [comment]
Can confirm this

**Comment by liamosycka** [comment]
I'm facing the same problem

**Comment by garymoon** [comment]
For now you can either use `appleboy/drone-scp:1.6.4` to pin the last release with an amd64 image, or use `appleboy/drone-scp:linux-amd64` for the latest available amd64 image.

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
Hi All,

Please try the `latest` tag again.

**Comment by garymoon** [comment]
I can confirm this is fixed, thanks @appleboy!

**Comment by sdvcrx** [comment]
@appleboy Hi! Maybe we could support multiple platforms docker image again ? 

Because `appleboy/drone-scp:1.6.4` works on both `arm64` and `amd64`, but `appleboy/drone-scp:latest` only supports `amd64`. it will be very helpful if support multiple platforms docker image.

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/5170232/210356963-a16a9a08-bb23-4e81-b251-a2370650df9d.png">
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/5170232/210357001-efa075cf-2bad-4aa0-a7c1-8eae1d30e0ed.png">
